-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 7, Failures: 2, Errors: 0, Skipped: 5, Time elapsed: 11.576 s <<< FAILURE! - in TestSuite
loginTrue(com.course.cases.LoginTest)  Time elapsed: 4.925 s  <<< FAILURE!
org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8888 refused
	at com.course.cases.LoginTest.getResult(LoginTest.java:87)
	at com.course.cases.LoginTest.loginTrue(LoginTest.java:47)
Caused by: java.net.ConnectException: Connection refused: connect
	at com.course.cases.LoginTest.getResult(LoginTest.java:87)
	at com.course.cases.LoginTest.loginTrue(LoginTest.java:47)

loginFalse(com.course.cases.LoginTest)  Time elapsed: 4.084 s  <<< FAILURE!
org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8888 refused
	at com.course.cases.LoginTest.getResult(LoginTest.java:87)
	at com.course.cases.LoginTest.loginFalse(LoginTest.java:64)
Caused by: java.net.ConnectException: Connection refused: connect
	at com.course.cases.LoginTest.getResult(LoginTest.java:87)
	at com.course.cases.LoginTest.loginFalse(LoginTest.java:64)

